### ISSUE TITLE
store reading accepts lower value that current reading

### ISSUE THREAD

**Issue by UtzM** [energychain/BusinessObject-MeterPointOperation#1]
![stromdao retrieve](https://user-images.githubusercontent.com/28506872/30525127-f29cd092-9c00-11e7-93e1-58a539a61491.JPG)

is this expected?

**Comment by zoernert** [comment]
Yes ... is expected as Charging/Discharging of storage (battery) would do exactly this. :) - But maybe a flag should be added to the tool itself to force a check.
